name: base45
description: A simple base45 library to perform utf8 string encoding and decoding. base45 is an internet draft and designed for efficient, compact encoding for QR code.
version: 0.0.2
repository: https://github.com/calvinchengx/base45

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.9
